name: test workflow
on:
  push:
    branches:
      - "*"
      - "**/*"
  pull_request:
jobs:
  run-windows-go-example:
    strategy:
      fail-fast: false
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: voicevox_coreの準備
        run: |
          Invoke-WebRequest https://github.com/VOICEVOX/voicevox_core/releases/latest/download/download-windows-x64.exe -OutFile ./download.exe
          ./download.exe
      - name: 必要ファイルの移動
        run: |
          cp -r   ./voicevox_core/model ./windows
          cp -r   ./voicevox_core/open_jtalk_dic_utf_8-1.11 ./windows
          cp  ./voicevox_core/onnxruntime.dll ./windows
          cp  ./voicevox_core/voicevox_core.dll ./windows
        working-directory: ./windows
      - name: Build
        run: go build
      - name: Run
        run: ./simple_tts
      - name: 音声ファイルの存在確認
        run: if exist speech.wav (exit 0) else (exit 1)
